version: '3.8'

services:
  resume-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-resume-generator
    ports:
      - "8765:8765"
    volumes:
      # Mount the output directories to persist generated PDFs on host
      - ./generated:/app/generated
      - ./output:/app/output
      # Mount resume data files to persist changes across container restarts
      - ./resume_data_enhanced.json:/app/resume_data_enhanced.json
      - ./resume_data_enhanced_DEFAULT.json:/app/resume_data_enhanced_DEFAULT.json
      - ./resume_backups:/app/resume_backups
      # Mount applications tracking to persist stats
      - ./applications_tracking.json:/app/applications_tracking.json
      # Optional: Mount .env file for API keys (if you prefer file-based config)
      - ./.env:/app/.env:ro
    environment:
      # Optional: Set API key via environment variable
      # Uncomment and set your key, or use .env file
      # - ANTHROPIC_API_KEY=your_api_key_here
      - STREAMLIT_SERVER_PORT=8765
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8765/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s